on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-24.04
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Hello World Docker Action
        id: hello
        uses: ranjithdb/hello-world-docker-action@v1
        with:
          who-to-greet: 'ran'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
